POST http://localhost:3333/register/user
Content-Type: application/json

{
  "name": "leonardo",
  "email": "leonardo@gmail.com",
  "password": "123456",
  "phone": "48999010353",
  "birthday": "12/04/2006"
}

###
POST http://localhost:3333/login/user
Content-Type: application/json

{
  "nameOrEmail": "leonardo",
  "password": "869"
}

###
POST http://localhost:3333/reset-password
Content-Type: application/json

{
  "email": "feliperossettodasilva123@gmail.com"
}
###
PUT http://localhost:3333/password-reset/5c4f19df-3e66-490c-b6a6-ac206a8aabea
Content-Type: application/json

{
  "password": "aabbcccoetp"
}